### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by mxiaoguang** [hongyang51/VideoPlayerManager#1]
java.lang.RuntimeException: this should be called in Main Thread
        at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:214)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3277)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by hongyang51** [comment]
@mmengchen  您可以修改一下这段代码 主线程更新 UI状态  最简单的方式 view.post(runnable);
